name: Lint Docs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check if source docs are changed
        id: changed-docs
        uses: tj-actions/changed-files@v29
        with:
          files: |
            packages/mermaid/src/docs/*
            packages/mermaid/src/docs.mts

      - uses: pnpm/action-setup@v2
        if: steps.changed-docs.outputs.only_modified == 'true'

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        if: steps.changed-docs.outputs.only_modified == 'true'
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        if: steps.changed-docs.outputs.only_modified == 'true'
        run: |
          pnpm install --frozen-lockfile
        env:
          CYPRESS_CACHE_FOLDER: .cache/Cypress

      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-docs.outputs.only_modified == 'true'
        run: |
          echo "Only files in the src/docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          yarn docs:build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        if: steps.changed-docs.outputs.only_modified == 'true'
        with:
          message: 'Update docs'
          add: 'docs/*'
